apiVersion: v1
kind: Namespace
metadata:
  name: airex-prod
  labels:
    name: airex-prod
    app.kubernetes.io/name: airex
    app.kubernetes.io/part-of: airex-platform
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
