apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: airex-api-pdb
  
  labels:
    app.kubernetes.io/name: airex
    app.kubernetes.io/component: api
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: airex
      app.kubernetes.io/component: api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: airex-web-pdb
  
  labels:
    app.kubernetes.io/name: airex
    app.kubernetes.io/component: web
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: airex
      app.kubernetes.io/component: web
